In [9]:
import numpy as np
import pandas as pd
import difflib #used to get closest matchind moviein case of spelling mistake
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
dataset=pd.read_csv("C:/Users/Sagar Dhyani/Downloads/DATASETS/IMBD movies.csv")
dataset.head()

poster  \
0  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1  https://m.media-amazon.com/images/S/sash/4Fyxw...   
2  https://m.media-amazon.com/images/S/sash/4Fyxw...   
3  https://m.media-amazon.com/images/S/sash/4Fyxw...   
4  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                      title certificate  runtime                      genre  \
0  The Shawshank Redemption          15  142 min                      Drama   
1           The Dark Knight         12A  152 min       Action, Crime, Drama   
2                 Inception         12A  148 min  Action, Adventure, Sci-Fi   
3                Fight Club          18  139 min                      Drama   
4              Pulp Fiction          18  154 min               Crime, Drama   

   rating                                              about  \
0     9.3  Two imprisoned men bond over a number of years...   
1     9.0  When the menace known as the Joker wreaks havo...   
2     8.8  A thief who steals corporate secrets through t...   
3     8.8  An insomniac office worker and a devil-may-car...   
4     8.9  The lives of two mob hitmen, a boxer, a gangst...   

            director                                              stars  \
0     Frank Darabont  ('Tim Robbins',), ('Morgan Freeman',), ('Bob G...   
1  Christopher Nolan  ('Christian Bale',), ('Heath Ledger',), ('Aaro...   
2  Christopher Nolan  ('Leonardo DiCaprio',), ('Joseph Gordon-Levitt...   
3      David Fincher  ('Brad Pitt',), ('Edward Norton',), ('Meat Loa...   
4  Quentin Tarantino  ('John Travolta',), ('Uma Thurman',), ('Samuel...   

       votes gross_earn  
0  26,26,905    $28.34M  
1  25,98,173   $534.86M  
2  23,04,062   $292.58M  
3  20,71,088    $37.03M  
4  20,11,013   $107.93M

In [12]:
dataset.shape

(5000, 11)

In [13]:
#selecting onlu revelent feature
selected_features=["genre","stars","director","about"] 
print(selected_features)

['genre', 'stars', 'director', 'about']


In [14]:
dataset.isnull().sum()

poster           0
title            0
certificate      0
runtime          0
genre           30
rating           0
about           14
director         0
stars            0
votes            0
gross_earn     415
dtype: int64

In [15]:
#replacing null values with null string

for features in selected_features:
    dataset[features]=dataset[features].fillna("")

In [16]:
'''sagar=["poster","title","certificate","runtime","about","votes","gross_earn"]
main_data=dataset.drop(sagar,axis=1)
main_data'''

'sagar=["poster","title","certificate","runtime","about","votes","gross_earn"]\nmain_data=dataset.drop(sagar,axis=1)\nmain_data'

In [17]:
#combine all the selected feature
combine_feature=dataset["genre"]+'  '+dataset["about"]+'    '+dataset["director"]+'    '+dataset["stars"]
combine_feature

0       Drama  Two imprisoned men bond over a number o...
1       Action, Crime, Drama  When the menace known as...
2       Action, Adventure, Sci-Fi  A thief who steals ...
3       Drama  An insomniac office worker and a devil-...
4       Crime, Drama  The lives of two mob hitmen, a b...
                              ...                        
4995    Comedy, Drama, Musical  In 1850 Oregon, when a...
4996    Comedy, Romance  Unrequited love motivates a g...
4997      A young couple's enduring love is tested whe...
4998    Comedy, Drama, Family  A 'pleasantly plump' te...
4999    Drama, Western  A gambler and a prostitute bec...
Length: 5000, dtype: object

In [18]:
#converting text data inot feature vector
vectorizer=TfidfVectorizer()

In [19]:
#feature_vector are the vector that are numerical type
feature_vector=vectorizer.fit_transform(combine_feature)

In [20]:
print(feature_vector)

  (0, 16797)	0.24355610434745792
  (0, 21029)	0.1411487444808571
  (0, 8336)	0.27177682560803823
  (0, 2375)	0.16455855657528637
  (0, 7408)	0.17143112632163102
  (0, 13078)	0.16601389214263193
  (0, 16465)	0.18837193322344514
  (0, 19470)	0.15008297480739535
  (0, 4796)	0.24355610434745792
  (0, 7359)	0.1506810299544407
  (0, 4937)	0.27177682560803823
  (0, 4002)	0.23319313889195292
  (0, 386)	0.23794080599826112
  (0, 19410)	0.14835548248541572
  (0, 15922)	0.20773237106533124
  (0, 6540)	0.27177682560803823
  (0, 910)	0.05203023324115255
  (0, 18039)	0.23794080599826112
  (0, 7068)	0.19398723157264194
  (0, 21337)	0.13662345287001557
  (0, 13901)	0.1012072101277977
  (0, 13797)	0.21184498737771726
  (0, 14196)	0.14835548248541572
  (0, 2440)	0.17143112632163102
  (0, 12605)	0.15453591361366806
  :	:
  (4999, 15369)	0.20101752443066614
  (4999, 12828)	0.22083053507401154
  (4999, 10315)	0.15910355180617025
  (4999, 16094)	0.18641601726967175
  (4999, 19646)	0.12313778372533751
  (499

In [21]:
#getting the similarity  scores using cosine similarity
'''what cosine similarity will do it will findout which movie is similar
and then on basis of similarity it will suggest the movie'''
similarity=cosine_similarity(feature_vector)

In [22]:
print(similarity)

[[1.         0.02069178 0.0327956  ... 0.00405651 0.01317668 0.02593078]
 [0.02069178 1.         0.10391508 ... 0.01157516 0.0078923  0.02304427]
 [0.0327956  0.10391508 1.         ... 0.01195795 0.         0.00984718]
 ...
 [0.00405651 0.01157516 0.01195795 ... 1.         0.00657461 0.01287531]
 [0.01317668 0.0078923  0.         ... 0.00657461 1.         0.00827685]
 [0.02593078 0.02304427 0.00984718 ... 0.01287531 0.00827685 1.        ]]


In [23]:
similarity.shape

(5000, 5000)

In [58]:
#getting movie name
movie_name=input("enter your fav movie: ")

enter your fav movie: Johnny English


In [59]:
#creating a list of all the movie given in the dataset
list_of_all_title=dataset["title"].tolist()
print(list_of_all_title)

['The Shawshank Redemption', 'The Dark Knight', 'Inception', 'Fight Club', 'Pulp Fiction', 'Forrest Gump', 'The Lord of the Rings: The Fellowship of the Ring', 'The Matrix', 'The Lord of the Rings: The Return of the King', 'The Godfather', 'The Dark Knight Rises', 'The Lord of the Rings: The Two Towers', 'Seven', 'Avengers Assemble', 'Gladiator', 'Batman Begins', 'Django Unchained', 'Interstellar', 'Star Wars', 'The Silence of the Lambs', 'Avatar', 'Inglourious Basterds', 'Saving Private Ryan', 'The Departed', "Schindler's List", 'Memento', 'The Prestige', 'Star Wars: Episode V - The Empire Strikes Back', 'American Beauty', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Titanic', 'V for Vendetta', 'The Godfather: Part II', 'Shutter Island', 'American History X', 'The Green Mile', 'The Wolf of Wall Street', 'Terminator 2: Judgment Day', 'The Usual Suspects', 'Braveheart', 'Kill Bill: Vol. 1', 'Back to the Future', 'Goodfellas', 'Leon', 'WALL·E', 'The Sixth Sense', 'The Hunge

In [60]:
##finding the close match for the movie name given by the user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_title)

In [61]:
print(find_close_match)

['Johnny English', 'Johnny English Reborn', 'Johnny Mnemonic']


In [53]:
dataset[dataset["title"]=="Calvary"]

poster    title certificate  \
2804  https://m.media-amazon.com/images/S/sash/4Fyxw...  Calvary          15   

      runtime                  genre  rating  \
2804  102 min  Crime, Drama, Mystery     7.4   

                                                  about  \
2804  After he is threatened during a confession, a ...   

                   director  \
2804  John Michael McDonagh   

                                                  stars   votes gross_earn  
2804  ('Brendan Gleeson',), ("Chris O'Dowd",), ('Kel...  59,385     $3.59M